import type {
  ApprenticeshipOffer,
  Alumni,
  CompanyNews,
} from "./types";

export const OFFERS: ApprenticeshipOffer[] = [
  {
    id: "1",
    title: "Alternant(e) Chef de Projet Marketing Digital",
    company: "LVMH",
    companyType: "grand-groupe",
    jobFamily: "marketing",
    location: "Paris 8e",
    duration: "24 mois",
    startDate: "Septembre 2025",
    salary: 1200,
    credibility: 5,
    description:
      "Rejoignez la direction marketing de LVMH et participez au développement de la stratégie digitale de nos maisons de luxe. Vous travaillerez sur des campagnes cross-canal, analyserez les performances et contribuerez à l'activation de nos marques sur les réseaux sociaux et plateformes e-commerce.",
    requirements: [
      "Bac+3/4 en marketing ou école de commerce",
      "Maîtrise des outils analytics (Google Analytics, Meta Ads)",
      "Créativité et sens de l'esthétique",
      "Anglais courant",
    ],
    postedDate: "2025-04-20",
    companyDescription:
      "LVMH est le leader mondial du luxe, rassemblant 75 maisons dans les vins et spiritueux, la mode, la parfumerie et cosmétiques, les montres et joaillerie, et la distribution sélective.",
    companyWebsite: "https://www.lvmh.fr",
    tags: ["luxe", "digital", "marketing", "stratégie"],
  },
  {
    id: "2",
    title: "Alternant(e) Analyste Financier",
    company: "BNP Paribas",
    companyType: "grand-groupe",
    jobFamily: "finance",
    location: "Paris 9e",
    duration: "24 mois",
    startDate: "Septembre 2025",
    salary: 1350,
    credibility: 5,
    description:
      "Au sein de la direction financière de BNP Paribas, vous participerez à l'analyse des performances financières, à l'élaboration des reportings et à la préparation des comités de direction. Excellente opportunité pour développer une expertise en finance d'entreprise dans un environnement international.",
    requirements: [
      "Bac+4/5 en finance ou école de commerce",
      "Maîtrise d'Excel et Power BI",
      "Rigueur et sens de l'analyse",
      "Anglais courant",
    ],
    postedDate: "2025-04-18",
    companyDescription:
      "BNP Paribas est la première banque de la zone euro, présente dans 65 pays avec plus de 180 000 collaborateurs. Acteur de référence en banque de détail, gestion d'actifs et banque de financement.",
    companyWebsite: "https://www.bnpparibas.com",
    tags: ["banque", "finance", "analyse", "reporting"],
  },
  {
    id: "3",
    title: "Alternant(e) Business Developer",
    company: "Alan",
    companyType: "startup",
    jobFamily: "commerce",
    location: "Paris 10e",
    duration: "12 mois",
    startDate: "Juillet 2025",
    salary: 1100,
    credibility: 4,
    description:
      "Alan est la licorne française de l'assurance santé. En tant que Business Developer, vous développerez le portefeuille clients PME/ETI, gérerez le cycle de vente complet et contribuerez à l'amélioration de notre processus commercial. Un rôle très opérationnel dans une scale-up ambitieuse.",
    requirements: [
      "Bac+3/4 en commerce ou école de commerce",
      "Goût du challenge commercial",
      "Excellentes qualités de communication",
      "Anglais courant",
    ],
    postedDate: "2025-04-22",
    companyDescription:
      "Alan est une insurtech française fondée en 2016 qui simplifie la santé en entreprise. Licorne valorisée à 4,5 Mds€, elle compte 500 000 assurés et est présente en France, en Belgique et en Espagne.",
    companyWebsite: "https://alan.com",
    tags: ["startup", "vente", "insurtech", "B2B"],
  },
  {
    id: "4",
    title: "Alternant(e) RH — Talent Acquisition",
    company: "L'Oréal",
    companyType: "grand-groupe",
    jobFamily: "rh",
    location: "Paris 17e",
    duration: "24 mois",
    startDate: "Septembre 2025",
    salary: 1200,
    credibility: 5,
    description:
      "Intégrez l'équipe Talent Acquisition de L'Oréal et participez au recrutement des meilleurs profils pour nos marques mondiales. Vous gérerez les campagnes de sourcing, conduirez les entretiens de présélection et accompagnerez les managers dans leurs prises de décision.",
    requirements: [
      "Bac+4/5 en RH, psychologie ou école de commerce",
      "Maîtrise des outils de sourcing (LinkedIn Recruiter, etc.)",
      "Sens de l'écoute et esprit d'équipe",
      "Anglais courant",
    ],
    postedDate: "2025-04-15",
    companyDescription:
      "L'Oréal est le leader mondial de la beauté, avec 38 marques internationales dans les cosmétiques, la coiffure et la parfumerie. Entreprise pionnière en RSE et diversité.",
    companyWebsite: "https://www.loreal.com",
    tags: ["beauté", "recrutement", "RH", "international"],
  },
  {
    id: "5",
    title: "Alternant(e) Chargé(e) de Communication",
    company: "Publicis Groupe",
    companyType: "grand-groupe",
    jobFamily: "communication",
    location: "Paris 8e",
    duration: "12 mois",
    startDate: "Septembre 2025",
    salary: 1050,
    credibility: 4,
    description:
      "Au sein du département communication de Publicis, vous contribuerez à la conception et à la mise en œuvre des stratégies de communication pour nos grands comptes. Rédaction de contenus, coordination avec les équipes créatives, suivi des campagnes et reporting.",
    requirements: [
      "Bac+3 à Bac+5 en communication ou école de commerce",
      "Excellentes qualités rédactionnelles en français",
      "Maîtrise de la suite Adobe (Photoshop, InDesign) appréciée",
      "Créativité et curiosité",
    ],
    postedDate: "2025-04-10",
    companyDescription:
      "Publicis Groupe est le 3e groupe de communication mondial, avec plus de 100 000 collaborateurs dans 100 pays. Il regroupe agences créatives, médias et conseil en transformation numérique.",
    companyWebsite: "https://www.publicisgroupe.com",
    tags: ["publicité", "communication", "agence", "grands comptes"],
  },
  {
    id: "6",
    title: "Alternant(e) Développeur(se) Full Stack",
    company: "Doctolib",
    companyType: "startup",
    jobFamily: "tech",
    location: "Paris 11e",
    duration: "12 mois",
    startDate: "Juin 2025",
    salary: 1400,
    credibility: 4,
    description:
      "Rejoignez l'équipe Engineering de Doctolib et contribuez au développement de la plateforme qui révolutionne l'accès aux soins de santé en Europe. Vous travaillerez sur des features à fort impact, en Ruby on Rails et React.",
    requirements: [
      "École d'ingénieurs ou Master informatique",
      "Expérience en Ruby on Rails et/ou React",
      "Goût pour les bonnes pratiques (TDD, code review)",
      "Anglais professionnel",
    ],
    postedDate: "2025-04-25",
    companyDescription:
      "Doctolib est la plateforme de santé leader en Europe. Fondée en 2013, elle compte plus de 75 millions de patients et 360 000 professionnels de santé. Sa mission : améliorer l'accès à la santé pour tous.",
    companyWebsite: "https://www.doctolib.fr",
    tags: ["healthtech", "dev", "Ruby", "React"],
  },
  {
    id: "7",
    title: "Alternant(e) Conseil en Management",
    company: "McKinsey & Company",
    companyType: "cabinet",
    jobFamily: "conseil",
    location: "Paris 8e",
    duration: "6 mois",
    startDate: "Septembre 2025",
    salary: 1800,
    credibility: 5,
    description:
      "Participez à des projets de transformation stratégique pour des clients du CAC40 et des acteurs publics. En tant qu'analyste alternant, vous accompagnerez les équipes de consultants dans les phases de diagnostic, d'analyse de données et de recommandations.",
    requirements: [
      "Grande école de commerce ou d'ingénieurs (M1/M2)",
      "Excellentes capacités analytiques",
      "Rigueur, autonomie et esprit de synthèse",
      "Anglais courant indispensable",
    ],
    postedDate: "2025-04-05",
    companyDescription:
      "McKinsey & Company est l'un des plus grands cabinets de conseil en management au monde, présent dans plus de 65 pays. Réputé pour sa rigueur analytique et sa capacité à résoudre les problèmes les plus complexes.",
    companyWebsite: "https://www.mckinsey.com",
    tags: ["conseil", "stratégie", "CAC40", "prestige"],
  },
  {
    id: "8",
    title: "Alternant(e) Category Manager",
    company: "Carrefour",
    companyType: "grand-groupe",
    jobFamily: "commerce",
    location: "Massy (92)",
    duration: "24 mois",
    startDate: "Septembre 2025",
    salary: 1150,
    credibility: 4,
    description:
      "En tant que Category Manager alternant, vous analyserez les performances des gammes de produits, proposerez des plans d'optimisation de l'assortiment et travaillerez avec nos fournisseurs. Poste très opérationnel au cœur de la stratégie commerciale.",
    requirements: [
      "Bac+4/5 en commerce, marketing ou école de commerce",
      "Appétence pour les chiffres et la grande distribution",
      "Excel avancé, Power BI apprécié",
      "Rigueur et sens de la négociation",
    ],
    postedDate: "2025-04-12",
    companyDescription:
      "Carrefour est le premier groupe de distribution en Europe et le deuxième mondial. Avec plus de 12 000 magasins dans 30 pays, Carrefour accompagne au quotidien les transitions alimentaires.",
    companyWebsite: "https://www.carrefour.com",
    tags: ["retail", "grande distribution", "category management", "achats"],
  },
  {
    id: "9",
    title: "Alternant(e) Chargé(e) de Marketing & Communication",
    company: "Shine",
    companyType: "startup",
    jobFamily: "marketing",
    location: "Paris 3e",
    duration: "12 mois",
    startDate: "Juillet 2025",
    salary: 950,
    credibility: 3,
    description:
      "Shine est la néobanque des indépendants. Vous rejoindrez une petite équipe marketing dynamique pour gérer les campagnes d'acquisition, créer des contenus engageants (blog, réseaux sociaux) et analyser les performances.",
    requirements: [
      "Bac+3/4 en marketing, communication ou école de commerce",
      "Créativité et sens de l'écriture",
      "Connaissance des outils CRM et marketing automation",
      "Curiosité pour la fintech",
    ],
    postedDate: "2025-04-28",
    companyDescription:
      "Shine est une fintech française qui simplifie la gestion administrative et financière des freelances et petites entreprises. Plus de 100 000 entrepreneurs lui font confiance.",
    companyWebsite: "https://www.shine.fr",
    tags: ["fintech", "startup", "content marketing", "réseaux sociaux"],
  },
  {
    id: "10",
    title: "Alternant(e) Chargé(e) de Ressources Humaines",
    company: "Capgemini",
    companyType: "grand-groupe",
    jobFamily: "rh",
    location: "Paris 15e",
    duration: "24 mois",
    startDate: "Septembre 2025",
    salary: 1100,
    credibility: 4,
    description:
      "Au sein de la direction RH de Capgemini France, vous interviendrez sur les sujets d'onboarding, de formation, de développement des compétences et de GPEC. Un rôle généraliste RH dans une grande ESN internationale.",
    requirements: [
      "Bac+4/5 en RH ou école de commerce option RH",
      "Bonne maîtrise des outils SIRH",
      "Sens du service et confidentialité",
      "Anglais opérationnel",
    ],
    postedDate: "2025-04-08",
    companyDescription:
      "Capgemini est un leader mondial du conseil, des services informatiques et de la transformation numérique, avec 340 000 collaborateurs dans plus de 50 pays.",
    companyWebsite: "https://www.capgemini.com",
    tags: ["ESN", "conseil", "RH", "formation"],
  },
  {
    id: "11",
    title: "Alternant(e) Juriste d'Affaires",
    company: "Total Energies",
    companyType: "grand-groupe",
    jobFamily: "juridique",
    location: "La Défense (92)",
    duration: "24 mois",
    startDate: "Septembre 2025",
    salary: 1300,
    credibility: 5,
    description:
      "Intégrez la direction juridique de TotalEnergies pour travailler sur des contrats commerciaux internationaux, des enjeux réglementaires liés à la transition énergétique et du droit des sociétés. Formation solide dans un environnement juridique exigeant.",
    requirements: [
      "Master 1 ou 2 en droit des affaires",
      "Capacité à analyser des documents juridiques complexes",
      "Anglais courant (contrats internationaux)",
      "Rigueur et réactivité",
    ],
    postedDate: "2025-04-14",
    companyDescription:
      "TotalEnergies est une compagnie multi-énergies mondiale qui produit et fournit énergies : pétrole, gaz naturel, électricités renouvelables. Elle emploie 100 000 personnes dans 130 pays.",
    companyWebsite: "https://www.totalenergies.com",
    tags: ["énergie", "droit", "international", "contrats"],
  },
  {
    id: "12",
    title: "Alternant(e) Supply Chain & Logistique",
    company: "Sodexo",
    companyType: "grand-groupe",
    jobFamily: "logistique",
    location: "Issy-les-Moulineaux (92)",
    duration: "24 mois",
    startDate: "Septembre 2025",
    salary: 1050,
    credibility: 3,
    description:
      "Rejoignez la direction Supply Chain de Sodexo pour optimiser les flux logistiques de nos services. Vous analyserez les indicateurs de performance, participerez à des projets d'amélioration continue et travaillerez avec nos équipes en région.",
    requirements: [
      "Bac+4/5 en supply chain, logistique ou école d'ingénieurs",
      "Maîtrise d'Excel, notions de Python ou SAP",
      "Esprit analytique et pragmatisme",
      "Permis B apprécié",
    ],
    postedDate: "2025-04-11",
    companyDescription:
      "Sodexo est un leader mondial des services de qualité de vie, présent dans 56 pays avec 412 000 collaborateurs. La société propose des services de restauration, d'accueil, de maintenance et d'avantages aux salariés.",
    companyWebsite: "https://www.sodexo.com",
    tags: ["logistique", "supply chain", "services", "amélioration continue"],
  },
  {
    id: "13",
    title: "Alternant(e) Marketing Produit",
    company: "Criteo",
    companyType: "grand-groupe",
    jobFamily: "marketing",
    location: "Paris 9e",
    duration: "12 mois",
    startDate: "Juillet 2025",
    salary: 1200,
    credibility: 4,
    description:
      "Criteo recherche un(e) alternant(e) Product Marketing pour accompagner le lancement de nouvelles fonctionnalités publicitaires. Vous travaillerez sur les messages produit, les supports de vente et la formation des équipes commerciales.",
    requirements: [
      "Bac+4/5 en marketing ou école de commerce",
      "Intérêt pour la publicité digitale et le retail media",
      "Capacité à créer des supports clairs et percutants",
      "Anglais courant",
    ],
    postedDate: "2025-04-23",
    companyDescription:
      "Criteo est une entreprise technologique française spécialisée dans le commerce publicitaire. Cotée au Nasdaq, elle accompagne plus de 22 000 annonceurs et partenaires dans le monde.",
    companyWebsite: "https://www.criteo.com",
    tags: ["adtech", "marketing produit", "retail media", "tech"],
  },
  {
    id: "14",
    title: "Alternant(e) Consultant(e) en Organisation",
    company: "Deloitte",
    companyType: "cabinet",
    jobFamily: "conseil",
    location: "Paris 1er",
    duration: "12 mois",
    startDate: "Septembre 2025",
    salary: 1400,
    credibility: 5,
    description:
      "Intégrez l'offre conseil de Deloitte pour travailler sur des projets de transformation organisationnelle, de conduite du changement et d'efficacité opérationnelle. Vous interviendrez sur des secteurs variés : secteur public, banque, assurance, industrie.",
    requirements: [
      "Grande école de commerce ou d'ingénieurs (M1/M2)",
      "Intérêt pour les enjeux d'organisation et de management",
      "Excellent relationnel et capacité d'adaptation",
      "Anglais courant",
    ],
    postedDate: "2025-04-07",
    companyDescription:
      "Deloitte est l'un des \"Big Four\", offrant des services de conseil, d'audit, de fiscalité et de gestion des risques à 90% des entreprises du Fortune 500.",
    companyWebsite: "https://www.deloitte.com",
    tags: ["Big4", "audit", "conseil", "transformation"],
  },
  {
    id: "15",
    title: "Alternant(e) Chargé(e) de Marketing B2B",
    company: "Salesforce",
    companyType: "grand-groupe",
    jobFamily: "marketing",
    location: "Paris 8e",
    duration: "12 mois",
    startDate: "Août 2025",
    salary: 1250,
    credibility: 5,
    description:
      "Au sein de l'équipe Marketing EMEA de Salesforce, vous contribuerez aux campagnes d'inbound marketing, à l'organisation d'événements professionnels et au développement des leads. Un poste idéal pour évoluer dans le marketing BtoB tech.",
    requirements: [
      "Bac+4/5 en marketing ou école de commerce",
      "Connaissance ou curiosité pour les solutions CRM",
      "Maîtrise de Salesforce Marketing Cloud ou Marketo appréciée",
      "Anglais courant",
    ],
    postedDate: "2025-04-17",
    companyDescription:
      "Salesforce est le leader mondial du CRM cloud, avec 79 000 employés dans le monde. Sa plateforme Customer 360 connecte toutes les équipes autour du client.",
    companyWebsite: "https://www.salesforce.com",
    tags: ["CRM", "marketing B2B", "tech", "SaaS"],
  },
  {
    id: "16",
    title: "Alternant(e) en Ressources Humaines",
    company: "Mairie de Paris",
    companyType: "public",
    jobFamily: "rh",
    location: "Paris 4e",
    duration: "24 mois",
    startDate: "Septembre 2025",
    salary: 900,
    credibility: 3,
    description:
      "Intégrez la direction des ressources humaines de la Ville de Paris. Vous participerez au pilotage de la GPEC, à la gestion des carrières des agents et aux projets de modernisation des pratiques RH au sein d'une des plus grandes collectivités de France.",
    requirements: [
      "Bac+4/5 en RH, droit public ou administration",
      "Intérêt pour le service public",
      "Organisation et rigueur administrative",
      "Discrétion et sens des responsabilités",
    ],
    postedDate: "2025-04-16",
    companyDescription:
      "La Mairie de Paris est la collectivité territoriale gérant la capitale française. Elle emploie 52 000 agents et est l'un des premiers employeurs de la région Île-de-France.",
    companyWebsite: "https://www.paris.fr",
    tags: ["secteur public", "collectivité", "RH", "service public"],
  },
  {
    id: "17",
    title: "Alternant(e) Growth Hacker",
    company: "Contentsquare",
    companyType: "startup",
    jobFamily: "marketing",
    location: "Paris 9e",
    duration: "12 mois",
    startDate: "Juillet 2025",
    salary: 1150,
    credibility: 4,
    description:
      "Contentsquare est une licorne française de l'analytique d'expérience digitale. Vous rejoindrez l'équipe Growth pour expérimenter des leviers d'acquisition, analyser les données d'engagement et optimiser les tunnels de conversion.",
    requirements: [
      "Bac+4/5 en marketing digital ou école de commerce",
      "Expérience avec des outils d'analytics (Mixpanel, Amplitude, etc.)",
      "Profil data-driven et créatif",
      "Anglais courant",
    ],
    postedDate: "2025-04-24",
    companyDescription:
      "Contentsquare est une plateforme d'analytique d'expérience utilisateur, valorisée à 5,6 Mds$. Ses solutions aident 1 200 marques mondiales à comprendre et améliorer l'expérience digitale de leurs clients.",
    companyWebsite: "https://www.contentsquare.com",
    tags: ["licorne", "growth hacking", "analytics", "digital"],
  },
  {
    id: "18",
    title: "Alternant(e) Finance d'Entreprise",
    company: "KPMG",
    companyType: "cabinet",
    jobFamily: "finance",
    location: "Paris 15e",
    duration: "12 mois",
    startDate: "Septembre 2025",
    salary: 1300,
    credibility: 5,
    description:
      "Rejoignez le département Audit & Conseil de KPMG France. Vous participerez à des missions d'audit légal, d'évaluation d'entreprises et de due diligence pour des clients grands comptes et mid-market dans des secteurs variés.",
    requirements: [
      "Master 1 ou 2 en finance, comptabilité ou école de commerce",
      "Maîtrise des outils de comptabilité",
      "Rigueur et sens du détail",
      "Anglais opérationnel",
    ],
    postedDate: "2025-04-06",
    companyDescription:
      "KPMG est l'un des \"Big Four\" de l'audit et du conseil. Présent dans 146 pays avec plus de 236 000 professionnels, KPMG accompagne les plus grandes organisations dans leur performance et leur transformation.",
    companyWebsite: "https://home.kpmg",
    tags: ["Big4", "audit", "finance", "comptabilité"],
  },
  {
    id: "19",
    title: "Alternant(e) Chef(fe) de Projet Événementiel",
    company: "GL Events",
    companyType: "pme",
    jobFamily: "communication",
    location: "Paris 20e",
    duration: "12 mois",
    startDate: "Juin 2025",
    salary: 950,
    credibility: 3,
    description:
      "Coordinatez des événements professionnels de A à Z : salons, conférences et congrès. Vous serez en contact direct avec les prestataires, les exposants et les équipes terrain. Poste très opérationnel avec une forte autonomie.",
    requirements: [
      "Bac+3/4 en événementiel, communication ou école de commerce",
      "Sens de l'organisation et gestion du stress",
      "Permis B apprécié",
      "Disponibilité les weekends lors des événements",
    ],
    postedDate: "2025-04-29",
    companyDescription:
      "GL Events est un acteur mondial de l'événementiel et de la gestion de sites, présent dans 23 pays. La société gère des espaces emblématiques et organise plus de 4 500 événements par an.",
    companyWebsite: "https://www.gl-events.com",
    tags: ["événementiel", "organisation", "communication", "logistique"],
  },
  {
    id: "20",
    title: "Alternant(e) Data Analyst",
    company: "BlaBlaCar",
    companyType: "startup",
    jobFamily: "tech",
    location: "Paris 2e",
    duration: "12 mois",
    startDate: "Juillet 2025",
    salary: 1200,
    credibility: 4,
    description:
      "BlaBlaCar recherche un(e) Data Analyst pour analyser les comportements utilisateurs et contribuer à l'amélioration des fonctionnalités de la plateforme. Vous travaillerez avec des données à grande échelle (SQL, Python) dans un environnement international.",
    requirements: [
      "École d'ingénieurs ou Master statistiques/data",
      "Maîtrise de SQL et Python (Pandas)",
      "Capacité à raconter une histoire avec des données",
      "Anglais courant",
    ],
    postedDate: "2025-04-26",
    companyDescription:
      "BlaBlaCar est le leader mondial du covoiturage longue distance, avec 90 millions de membres dans 22 pays. La startup française connecte voyageurs et conducteurs pour rendre les déplacements plus durables.",
    companyWebsite: "https://www.blablacar.fr",
    tags: ["mobilité", "data", "SQL", "Python"],
  },
  {
    id: "21",
    title: "Alternant(e) Responsable de Rayon",
    company: "Monoprix",
    companyType: "grand-groupe",
    jobFamily: "commerce",
    location: "Paris Centre",
    duration: "24 mois",
    startDate: "Septembre 2025",
    salary: 1000,
    credibility: 3,
    description:
      "Gérez l'un des rayons d'un magasin Monoprix parisien en tant que futur(e) manager terrain. Vous serez responsable des commandes, de la mise en rayon, de la gestion des stocks et de l'animation d'une équipe.",
    requirements: [
      "Bac+3/4 en commerce ou management",
      "Leadership et sens du service client",
      "Disponibilité (horaires décalés possibles)",
      "Première expérience en retail appréciée",
    ],
    postedDate: "2025-04-19",
    companyDescription:
      "Monoprix est une chaîne de distribution française spécialisée en centre-ville et appartenant au groupe Casino. Avec 350 magasins, elle occupe une place unique dans la distribution urbaine.",
    companyWebsite: "https://www.monoprix.fr",
    tags: ["retail", "management", "grande distribution", "opérationnel"],
  },
  {
    id: "22",
    title: "Alternant(e) Chargé(e) de Mission RSE",
    company: "Danone",
    companyType: "grand-groupe",
    jobFamily: "conseil",
    location: "Paris 17e",
    duration: "24 mois",
    startDate: "Septembre 2025",
    salary: 1150,
    credibility: 4,
    description:
      "Au sein de la direction RSE de Danone, vous contribuerez au déploiement de la stratégie d'impact du groupe : bilan carbone, reporting extra-financier, programmes d'engagement des collaborateurs et relations avec les parties prenantes.",
    requirements: [
      "Bac+4/5 en développement durable, école de commerce ou d'ingénieurs",
      "Connaissance des référentiels RSE (GRI, CSRD)",
      "Curiosité et sens de l'initiative",
      "Anglais courant",
    ],
    postedDate: "2025-04-09",
    companyDescription:
      "Danone est un leader mondial de l'alimentation et des boissons saines, avec des marques comme Evian, Activia et Aptamil. Premier grand groupe certifié B Corp au monde.",
    companyWebsite: "https://www.danone.com",
    tags: ["RSE", "développement durable", "agroalimentaire", "impact"],
  },
  {
    id: "23",
    title: "Alternant(e) Conseiller(e) de Vente Luxe",
    company: "Sephora",
    companyType: "grand-groupe",
    jobFamily: "commerce",
    location: "Paris Champs-Élysées",
    duration: "12 mois",
    startDate: "Juillet 2025",
    salary: 1000,
    credibility: 3,
    description:
      "Devenez ambassadeur(drice) de la beauté dans l'un des plus beaux flagships Sephora des Champs-Élysées. Vous conseillerez les clients, gérerez les stocks et contribuerez aux animations commerciales.",
    requirements: [
      "BTS ou Bac+3 en vente, commerce ou cosmétique",
      "Passion pour la beauté",
      "Excellent sens du service client",
      "Dynamisme et esprit d'équipe",
    ],
    postedDate: "2025-04-21",
    companyDescription:
      "Sephora est la chaîne de distribution de cosmétiques leader du groupe LVMH, présente dans 35 pays avec 3 000 magasins. Véritable temple de la beauté, elle représente plus de 400 marques.",
    companyWebsite: "https://www.sephora.fr",
    tags: ["luxe", "beauté", "retail", "service client"],
  },
  {
    id: "24",
    title: "Alternant(e) Chef(fe) de Projet Transformation Digitale",
    company: "Orange",
    companyType: "grand-groupe",
    jobFamily: "tech",
    location: "Paris 15e",
    duration: "24 mois",
    startDate: "Septembre 2025",
    salary: 1250,
    credibility: 4,
    description:
      "Pilotez des projets de transformation digitale au sein de la DSI d'Orange. Vous travaillerez avec les équipes métier pour digitaliser les processus internes, déployer de nouveaux outils et accompagner le changement auprès des utilisateurs.",
    requirements: [
      "Bac+4/5 en informatique, école d'ingénieurs ou de commerce",
      "Connaissance des méthodes agiles",
      "Qualités relationnelles et capacité à convaincre",
      "Anglais professionnel",
    ],
    postedDate: "2025-04-13",
    companyDescription:
      "Orange est l'un des principaux opérateurs de télécommunications mondiaux avec 136 000 salariés et 300 millions de clients. Il accélère sa transformation digitale et dans les nouvelles technologies.",
    companyWebsite: "https://www.orange.com",
    tags: ["télécom", "digital", "transformation", "projet"],
  },
  {
    id: "25",
    title: "Alternant(e) en Comptabilité & Finance",
    company: "Cabinet Mazars",
    companyType: "cabinet",
    jobFamily: "finance",
    location: "Paris 8e",
    duration: "24 mois",
    startDate: "Septembre 2025",
    salary: 1200,
    credibility: 4,
    description:
      "Intégrez le département Audit de Mazars pour participer à des missions d'audit légal et contractuel auprès de PME et grandes entreprises. Formation complète assurée pour préparer votre diplôme d'expertise comptable.",
    requirements: [
      "DCG ou Bac+4 en comptabilité, finance ou droit des affaires",
      "Sérieux, méthode et précision",
      "Maîtrise de l'environnement comptable",
      "Mobilité en Île-de-France",
    ],
    postedDate: "2025-04-03",
    companyDescription:
      "Mazars est un cabinet international d'audit, de fiscalité et de conseil, présent dans 95 pays avec 50 000 professionnels. Reconnu pour son approche humaine et sa culture de l'excellence.",
    companyWebsite: "https://www.mazars.fr",
    tags: ["audit", "expertise comptable", "finance", "cabinet"],
  },
];

export const ALUMNI: Alumni[] = [
  // LVMH
  {
    id: "a1",
    name: "Sophie Marchand",
    role: "Brand Manager",
    company: "LVMH",
    graduationYear: 2022,
    program: "MSc Marketing & Luxe",
    linkedinUrl: "#",
    avatarInitials: "SM",
  },
  {
    id: "a2",
    name: "Théo Blanchard",
    role: "Chargé CRM",
    company: "LVMH",
    graduationYear: 2023,
    program: "Bachelor Commerce International",
    linkedinUrl: "#",
    avatarInitials: "TB",
  },
  // BNP Paribas
  {
    id: "a3",
    name: "Emma Rousseau",
    role: "Analyste Financement",
    company: "BNP Paribas",
    graduationYear: 2021,
    program: "MSc Finance d'Entreprise",
    linkedinUrl: "#",
    avatarInitials: "ER",
  },
  // L'Oréal
  {
    id: "a4",
    name: "Lucas Fontaine",
    role: "HRBP Junior",
    company: "L'Oréal",
    graduationYear: 2022,
    program: "MSc Management RH",
    linkedinUrl: "#",
    avatarInitials: "LF",
  },
  // Capgemini
  {
    id: "a5",
    name: "Chloé Bernard",
    role: "Consultante RH",
    company: "Capgemini",
    graduationYear: 2023,
    program: "Bachelor RH & Management",
    linkedinUrl: "#",
    avatarInitials: "CB",
  },
  {
    id: "a6",
    name: "Antoine Girard",
    role: "Business Analyst",
    company: "Capgemini",
    graduationYear: 2022,
    program: "MSc Management des SI",
    linkedinUrl: "#",
    avatarInitials: "AG",
  },
  // McKinsey
  {
    id: "a7",
    name: "Inès Dupont",
    role: "Business Analyst",
    company: "McKinsey & Company",
    graduationYear: 2023,
    program: "Grande École — Programme Grande École",
    linkedinUrl: "#",
    avatarInitials: "ID",
  },
  // Deloitte
  {
    id: "a8",
    name: "Mathieu Leroy",
    role: "Auditeur Senior",
    company: "Deloitte",
    graduationYear: 2020,
    program: "MSc Finance & Contrôle",
    linkedinUrl: "#",
    avatarInitials: "ML",
  },
  // Salesforce
  {
    id: "a9",
    name: "Camille Petit",
    role: "Marketing Manager EMEA",
    company: "Salesforce",
    graduationYear: 2021,
    program: "MSc Marketing Digital",
    linkedinUrl: "#",
    avatarInitials: "CP",
  },
  // Doctolib
  {
    id: "a10",
    name: "Romain Lefebvre",
    role: "Growth Manager",
    company: "Doctolib",
    graduationYear: 2022,
    program: "Bachelor Marketing & Digital",
    linkedinUrl: "#",
    avatarInitials: "RL",
  },
  // Alan
  {
    id: "a11",
    name: "Jade Martin",
    role: "Account Executive",
    company: "Alan",
    graduationYear: 2023,
    program: "Bachelor Commerce",
    linkedinUrl: "#",
    avatarInitials: "JM",
  },
  // KPMG
  {
    id: "a12",
    name: "Hugo Moreau",
    role: "Auditeur Confirmé",
    company: "KPMG",
    graduationYear: 2021,
    program: "MSc Audit & Expertise Comptable",
    linkedinUrl: "#",
    avatarInitials: "HM",
  },
  // Danone
  {
    id: "a13",
    name: "Léa Simon",
    role: "Chef de Projet RSE",
    company: "Danone",
    graduationYear: 2022,
    program: "MSc Stratégie & RSE",
    linkedinUrl: "#",
    avatarInitials: "LS",
  },
  // Publicis
  {
    id: "a14",
    name: "Alexis Dubois",
    role: "Strategic Planner",
    company: "Publicis Groupe",
    graduationYear: 2022,
    program: "MSc Communication & Stratégie",
    linkedinUrl: "#",
    avatarInitials: "AD",
  },
  // Contentsquare
  {
    id: "a15",
    name: "Nina Patel",
    role: "Customer Success Manager",
    company: "Contentsquare",
    graduationYear: 2023,
    program: "Bachelor Marketing International",
    linkedinUrl: "#",
    avatarInitials: "NP",
  },
];

export const COMPANY_NEWS: CompanyNews[] = [
  // LVMH
  {
    id: "n1",
    company: "LVMH",
    title: "LVMH annonce un chiffre d'affaires record de 86 Mds€ en 2024",
    summary: "Le groupe de luxe a dépassé ses objectifs annuels avec une croissance de 9%, portée par les maisons de mode-cuir et les vins et spiritueux.",
    date: "2025-01-28",
    source: "Les Échos",
    type: "finance",
  },
  {
    id: "n2",
    company: "LVMH",
    title: "LVMH renforce son programme de recrutement de jeunes talents",
    summary: "Le groupe prévoit de recruter 5 000 alternants en France en 2025, doublant son engagement en faveur de l'apprentissage.",
    date: "2025-03-15",
    source: "Le Figaro",
    type: "recruitment",
  },
  // BNP Paribas
  {
    id: "n3",
    company: "BNP Paribas",
    title: "BNP Paribas lance son plan stratégique 2025–2027 « GTS »",
    summary: "La banque ambitionne d'accélérer sa croissance en banque de détail et sur les marchés de capitaux, avec 1,5 Md€ d'investissements technologiques.",
    date: "2025-02-12",
    source: "BFM Business",
    type: "general",
  },
  // Alan
  {
    id: "n4",
    company: "Alan",
    title: "Alan dépasse les 500 000 assurés et lève 183 M€",
    summary: "La scale-up insurtech confirme sa trajectoire de croissance et annonce une nouvelle levée de fonds pour financer son expansion en Europe.",
    date: "2025-04-01",
    source: "TechCrunch",
    type: "finance",
  },
  // L'Oréal
  {
    id: "n5",
    company: "L'Oréal",
    title: "L'Oréal accélère sur la beauté durable et les cosmétiques de demain",
    summary: "Le groupe dévoile sa nouvelle stratégie RSE « L'Oréal for the Future », avec un investissement de 1 Md€ sur 5 ans dans l'économie circulaire.",
    date: "2025-03-05",
    source: "Le Monde",
    type: "rse",
  },
  // Doctolib
  {
    id: "n6",
    company: "Doctolib",
    title: "Doctolib intègre l'IA générative pour les comptes-rendus médicaux",
    summary: "La licorne française déploie un outil d'assistance à la rédaction pour réduire la charge administrative des médecins et améliorer la prise en charge.",
    date: "2025-04-10",
    source: "Les Échos",
    type: "innovation",
  },
  // Capgemini
  {
    id: "n7",
    company: "Capgemini",
    title: "Capgemini maintient ses objectifs de 2025 et recrute 15 000 personnes en France",
    summary: "Malgré un contexte macroéconomique difficile, le groupe affiche une résilience et continue d'investir dans les talents tech et data.",
    date: "2025-02-20",
    source: "Reuters",
    type: "recruitment",
  },
  // McKinsey
  {
    id: "n8",
    company: "McKinsey & Company",
    title: "McKinsey publie son rapport sur la transformation des entreprises françaises",
    summary: "Le cabinet identifie la transition digitale et écologique comme les deux principaux leviers de compétitivité pour les 5 prochaines années.",
    date: "2025-03-22",
    source: "McKinsey.com",
    type: "general",
  },
  // Deloitte
  {
    id: "n9",
    company: "Deloitte",
    title: "Deloitte France recrute 3 500 collaborateurs en 2025",
    summary: "Le cabinet renforce ses équipes en audit, conseil et juridique-fiscal, avec un accent sur les profils data et IA.",
    date: "2025-03-18",
    source: "Deloitte.fr",
    type: "recruitment",
  },
  // Publicis
  {
    id: "n10",
    company: "Publicis Groupe",
    title: "Publicis Groupe acquiert Accenture Interactive pour renforcer le conseil data",
    summary: "Le groupe de communication consolide sa position dans le data-driven marketing avec cette opération stratégique estimée à 3 Mds€.",
    date: "2025-01-30",
    source: "Challenges",
    type: "general",
  },
  // Criteo
  {
    id: "n11",
    company: "Criteo",
    title: "Criteo renforce sa plateforme retail media et dépasse 1 Md$ de revenus",
    summary: "Criteo affiche une forte croissance sur le segment retail media, avec de nouveaux partenariats avec Amazon et Walmart.",
    date: "2025-02-08",
    source: "AdWeek",
    type: "finance",
  },
  // Danone
  {
    id: "n12",
    company: "Danone",
    title: "Danone renouvelle sa certification B Corp et renforce ses engagements sociaux",
    summary: "Premier groupe mondial certifié B Corp, Danone publie son rapport d'impact avec des avancées sur l'alimentation durable et les conditions de travail.",
    date: "2025-04-15",
    source: "Novethic",
    type: "rse",
  },
  // Salesforce
  {
    id: "n13",
    company: "Salesforce",
    title: "Salesforce intègre AgentForce dans toute sa plateforme CRM",
    summary: "Salesforce accélère le déploiement de ses agents IA autonomes pour transformer les workflows de ses 150 000 clients mondiaux.",
    date: "2025-03-28",
    source: "Tech.co",
    type: "innovation",
  },
  // Contentsquare
  {
    id: "n14",
    company: "Contentsquare",
    title: "Contentsquare lève 200 M$ pour accélérer à l'international",
    summary: "La licorne parisienne annonce un nouveau tour de table pour développer ses capacités en IA et s'implanter en Asie-Pacifique.",
    date: "2025-04-05",
    source: "Maddyness",
    type: "finance",
  },
  // KPMG
  {
    id: "n15",
    company: "KPMG",
    title: "KPMG France remporte les prix Employer of Choice et Top Employeur",
    summary: "Le cabinet confirme son attractivité avec ces deux labels en matière d'environnement de travail, de développement des talents et de diversité.",
    date: "2025-01-15",
    source: "KPMG.fr",
    type: "recruitment",
  },
];
